version: 1.0
app:
  instances: 1
  version: 20c21a85-2c87-432e-9e11-8a902d921c5d
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
