version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: 170060a0-9a8b-4f39-93a2-13a806676b65
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
