version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: ea974415-ee11-4101-9606-113ec521fd57
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
