version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: f0524adb-503b-4795-ac06-6ebcb76cadef
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
