version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: 37f4fb26-d8ff-4cdf-8919-d89ac081c626
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
