version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: e3d0f089-1dd4-4fc1-b189-0a64596fc438
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
