version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: 4ac39fc8-0634-4464-8fd3-a6fe0b2446f9
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
