version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: "b4bdd594-a4c4-4642-9a08-c67c45502910"
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
