version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: 1586e2e8-1396-433b-8075-adcefdc56902
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
