version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: "a88102e7-0c11-4cae-8dda-595d928e9cf3"
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
