version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: 63c9659d-8436-4db4-a0b7-d28bd1f19537
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
