version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: "4eeb3c9a-1c52-4824-9597-97d292daf13c"
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
