version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: 3f57f048-5a68-47b3-9b44-c1aa32257053
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
