version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: 4a75c0c3-65c4-41c8-82c3-c85e72086a17
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
