version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: 948df41f-79e3-438a-a5d1-12f81a935dc0
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
