version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: 48cca2d6-2c2b-4ea5-ab2d-a40aa90a2a44
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
